name: Create executable file and new release

on:
  push:
    tags:
      - '[0-9]**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Retrieve program
      uses: actions/checkout@v3
      with:
        ref: main
    
    - name: Create executable with Pyinstaller
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .
        spec: bwproxy_win.spec
        requirements: requirements.txt
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: bwproxy_win
        path: dist/windows/bwproxy-gui.exe
        
    - name: Release and upload executable
      if: ${{ success() }}
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          dist/windows/bwproxy-gui.exe